### ISSUE TITLE
SPDX expression for pyproject.toml

### ISSUE THREAD

**Issue by hyandell** [cvs-health/langfair#55]
**Describe the bug**
Small item, but I think it would be more correct to have "Apache-2.0 AND MIT" in the pyproject.toml. Commas are always confusing as to whether they mean OR or AND, and so the SPDX expression is more explicit.

**Comment by dylanbouchard** [comment]
Thank you very much for creating this issue. We will fix this in the next release.

**Comment by dylanbouchard** [comment]
This issue is fixed as of [release v0.2.1](https://github.com/cvs-health/langfair/releases/tag/v0.2.1)
